spring:
  application:
    name: historico-service
  datasource:
    #url: jdbc:postgresql://localhost:5432/historico-database
    url: jdbc:postgresql://postgres-historico:5432/historico-database
    username: postgres
    password: senha
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    #host: localhost
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    exchange: historico.exchange
    queues:
      historicoCreatedQueue: historico.created.queue
      historicoUpdatedQueue: historico.updated.queue
server:
  port: 8082
eureka:
  client:
    service-url:
      #defaultZone: http://localhost:8761/eureka/
      defaultZone: http://eureka-server:8761/eureka/
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html