spring:
  application:
    name: produto-service
  datasource:
    url: jdbc:postgresql://localhost:5432/produto-database
    username: postgres
    password: senha
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    exchange: product.exchange
    queues:
      productCreatedQueue: product.created.queue
      productUpdatedQueue: product.updated.queue
      productDeletedQueue: product.deleted.queue
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/