spring:
  application:
    name: estoque-service
  datasource:
    url: jdbc:postgresql://localhost:5432/estoque-database
    username: postgres
    password: senha
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    exchange: stock.exchange
    queues:
      stockCreatedQueue: stock.created.queue
      stockUpdatedQueue: stock.updated.queue
      stockDeletedQueue: stock.deleted.queue
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html